branch-defaults:
  default:
    environment: liferay-game-dev
    group_suffix: null
  master:
    environment: liferay-game-dev
global:
  application_name: liferay-game
  branch: master
  default_ec2_keyname: aws-eb
  default_platform: Multi-container Docker 17.03.2-ce (Generic)
  default_region: eu-west-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
